export const URLprofile = 'https://tutoacademy-profile-ms-oadjztiq2a-uc.a.run.app'
export const URLchat = 'https://tutoacademy-chat-ms-oadjztiq2a-uc.a.run.app'
export const URLmeetsched = 'https://tutoacademy-meetsched-ms-oadjztiq2a-uc.a.run.app'
export const URLtutorservice = 'https://tutoacademy-tutorservice-ms-oadjztiq2a-uc.a.run.app'
export const URLauth = 'https://tutoacademy-auth-ms-oadjztiq2a-uc.a.run.app'
export const URLsourcelambda = 'http://35.208.88.188/GetPosts?wsdl'